#!/bin/bash
# Created by Batah Marayau
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
echo "Connecting To VPN888™ System....."
sleep 0.2
clear
echo "Please Wait....."
sleep 0.5
echo "Generating Account....."
sleep 0.5
echo "Generating Host....."
sleep 0.5
echo "Generating Username....."
sleep 0.5
echo "Generating Password....."
sleep 1
MYIP=$(wget -qO- ipv4.icanhazip.com)
passrandom=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)

username=trial
egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
# proses mengganti password
  echo -e "$passrandom\n$passrandom" | passwd $username
  clear
  echo " "
  echo "Details For Trial Account"
  echo "------------------------------"
  echo " " 
  echo "   Username : $username"
  echo "   Password : $passrandom"
  echo " "
  echo "------------------------------"
  echo " "
  
else
  useradd trial
  usermod -s /bin/false trial
  egrep "^$username" /etc/passwd >/dev/null
  echo -e "$passrandom\n$passrandom" | passwd $username
  clear
  echo " "
  echo "Details For Trial Account"
  echo "------------------------------"
  echo " "
  echo "   Username : $username"
  echo "   Password : $passrandom"
  echo " "
  echo "------------------------------"
  echo " "
fi
