#!/bin/bash
red='\e[1;31m'
green='\e[0;32m'
blue='\e[1;34m'
NC='\e[0m'
echo "Connecting To VPN888™ System....."
sleep 0.2
read -p "Enter Username : " username
egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
read -p "Enter New Password For User $username : " password

clear
echo "Connecting To VPN888™ System....."
sleep 0.5
echo "Changing Password....."
sleep 0.5
  egrep "^$username" /etc/passwd >/dev/null
  echo -e "$password\n$password" | passwd $username
  clear
  echo " "
  echo "---------------------------------------"
  echo -e "Password For ${blue}$username${NC} Sucsesfully Change"
  echo -e "New Password For ${blue}$username${NC} Is ${red}$password${NC}"
  echo "--------------------------------------"
  echo " "

else
echo -e "Username ${red}$username${NC} Not Found On Server"
exit 0
fi
